### ISSUE TITLE
MIMCLogger 能否提供 设置日志路径，控制台输出，全局开关的接口？

### ISSUE THREAD

**Issue by Lee-swifter** [Xiaomi-mimc/mimc-android-sdk#3]
如果 MIMCLogger 能够提供上面几个基本的方法的话，接入时就基本没必要做其他的 Log 处理了，不知道小米能否提供呢？

**Comment by nayexinqing** [comment]
控制台输出、全局开关本身支持，日志在应用的安装路径下，demo会尽快把控制台输出更新上去。

**Comment by nayexinqing** [comment]
为什么需要设置日志路径？

**Comment by nayexinqing** [comment]
已更新

**Comment by Lee-swifter** [comment]
设置日志路径主要是因为测试时都是直接从手机存储中导出log文件，设置一个简单的路径能够方便测试人员处理。而且如果路径在应用路径下，设备还需要root才能看到。。。

**Comment by nayexinqing** [comment]
不需要root的，可以直接导出
